# Generated by Django 4.0.3 on 2022-04-20 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='bonus',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='profit',
            field=models.FloatField(default=0.0),
        ),
    ]
