# Generated by Django 4.0 on 2022-05-26 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_dashboard_bonus_dashboard_profit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dashboard',
            old_name='btc',
            new_name='deposit',
        ),
        migrations.RemoveField(
            model_name='dashboard',
            name='eth',
        ),
        migrations.RemoveField(
            model_name='dashboard',
            name='usd',
        ),
    ]
